# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rake/testtask'
require 'rubocop/rake_task'

Rake::TestTask.new do |t|
  t.ruby_opts += ['-W1']
  t.pattern = 'spec/*_spec.rb'
end

RuboCop::RakeTask.new

task default: %i[test rubocop]
